# See https://cloud.google.com/cloud-build/docs/build-config
steps:
- name: gcr.io/cloud-builders/docker
  entrypoint: /usr/bin/make
  args:
    - push-images
    - TAG=$_GIT_TAG
substitutions:
  # variables set by kubernetes/test-infra/images/builder
  # set by image-builder to vYYYYMMDD-hash
  _GIT_TAG: "12345"
