run:
  timeout: 2m

linters:
  disable-all: true
  enable:
    # default golangci-lint lints
    # NOTE: https://github.com/golangci/golangci-lint/issues/1841
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - typecheck
    # TODO: reenable, seems to be broken in go 1.18
    # keep an eye on https://github.com/golangci/golangci-lint/issues/2649
    #- unused

    # additional lints
    - gochecknoinits
    - gofmt
    - gosec
    - revive # replaces golint for now
    - misspell
    - exportloopref
    - unparam

linters-settings:
