name: Archeio Unit Test

on: push

jobs:
  archeio_unit_test:
    runs-on: ubuntu-latest
    if: github.event_name == 'push'

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
      - name: run unit tests
        run: |
          cd cmd/archeio
          go test
